[package]
name = "zizmor-sarif"
description = "Minimal SARIF 2.1.0 data models used by zizmor"
readme = "README.md"
repository = "https://github.com/zizmorcore/zizmor/tree/main/crates/zizmor-sarif"

version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[lints]
workspace = true
