[package]
name = "yamlpath"
description = "Format-preserving YAML feature extraction"
readme = "README.md"
repository = "https://github.com/zizmorcore/zizmor/tree/main/crates/yamlpath"
keywords = ["yaml"]

version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
line-index.workspace = true
self_cell.workspace = true
serde.workspace = true
thiserror.workspace = true
tree-sitter.workspace = true
tree-sitter-iter = { workspace = true }
tree-sitter-yaml = { workspace = true }

[dev-dependencies]
yaml_serde.workspace = true

[lints]
workspace = true
