[package]
name = "zizmor"
description = "Static analysis for GitHub Actions"
documentation = "https://docs.zizmor.sh"
repository = "https://github.com/zizmorcore/zizmor"
keywords = ["cli", "github-actions", "security", "static-analysis"]
categories = ["command-line-utilities", "security"]

version.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
annotate-snippets.workspace = true
anstream.workspace = true
anyhow.workspace = true
camino = { workspace = true, features = ["serde1"] }
clap = { workspace = true, features = ["derive", "env"] }
futures.workspace = true
human-panic.workspace = true
indicatif.workspace = true
itertools.workspace = true
owo-colors.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
terminal-link.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-std", "rt-multi-thread"] }
tower-lsp-server = { workspace = true, optional = true }
tracing.workspace = true
tracing-indicatif.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
zizmor-audit.workspace = true
zizmor-cli.workspace = true
zizmor-collect.workspace = true
zizmor-config.workspace = true
zizmor-core.workspace = true
zizmor-sarif.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
insta.workspace = true
regex.workspace = true
similar.workspace = true
tempfile.workspace = true
walkdir.workspace = true

[target.'cfg(not(any(target_family = "windows", target_os = "openbsd")))'.dependencies]
tikv-jemallocator.workspace = true

[features]
default = ["lsp"]
# Test-only: enable 'crater' tests.
crater-tests = ["online-tests"]
# Test-only: enable online audits that make use of a GitHub token via GH_TOKEN.
gh-token-tests = ["zizmor-core/gh-token-tests"]
lsp = ["dep:tower-lsp-server", "zizmor-cli/lsp"]
# Test-only: enable all online audits.
online-tests = ["gh-token-tests", "zizmor-audit/online-tests"]
# Enable JSON Schema generation for zizmor.yml
schema = ["zizmor-cli/schema", "zizmor-config/schema"]
# Test-only: enable tests that require `unbuffer` for TTY behavior.
tty-tests = []

[lints]
workspace = true
