[package]
name = "tree-sitter-iter"
description = "A very simple pre-order iterator for tree-sitter CSTs"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
tree-sitter.workspace = true

[dev-dependencies]
tree-sitter-yaml = { workspace = true }

[lints]
workspace = true
