[package]
name = "yamlpatch"
description = "Comment and format-preserving YAML patch operations"
repository = "https://github.com/zizmorcore/zizmor/tree/main/crates/yamlpatch"
keywords = ["patch", "yaml"]

version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
line-index.workspace = true
serde_json.workspace = true
subfeature.workspace = true
thiserror.workspace = true
yaml_serde.workspace = true
yamlpath.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
