[package]
name = "github-actions-models"
description = "Unofficial, high-quality data models for GitHub Actions workflows, actions, and related components"
readme = "README.md"
repository = "https://github.com/zizmorcore/zizmor/tree/main/crates/github-actions-models"
keywords = ["ci", "github"]
categories = ["api-bindings"]

version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
self_cell.workspace = true
serde.workspace = true
tracing.workspace = true
yaml_serde.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
