name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Run benchmarks
    # PRs only get benchmarked if they have the `run-benchmarks` label.
    # Forks don't have access to CodSpeed secrets, so skip them.
    if: |
      github.repository_owner == 'zizmorcore'
        && (contains(github.event.pull_request.labels.*.name, 'run-benchmarks')
          || github.event_name == 'push'
          || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-all-crates: true

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Build zizmor (release)
        run: cargo build --release

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        with:
          mode: walltime
          run: make bench
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
