[package]
name = "subfeature"
description = "Subfeature handling and manipulation APIs"
readme = "README.md"
repository = "https://github.com/zizmorcore/zizmor/tree/main/crates/subfeature"

version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
memchr.workspace = true
regex.workspace = true
serde.workspace = true

[lints]
workspace = true
